# Generated by Django 4.1.1 on 2022-09-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todolist_created_on_todoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="%A, %B %e, %Y"
            ),
        ),
    ]
